### ISSUE TITLE
CANT REUSE BLUEBOMB

### ISSUE THREAD

**Issue by holadivinus** [Fullmetal5/bluebomb#13]
Once you've useb bluebomb once, you cant use it again.
WHAT THE HECK
just because i messed it up the first time do i have to reinstall EVERYTHING?

**Comment by holadivinus** [comment]
what i try/get:

pi@skeet:~ $ sudo ./bluebomb-arm ./stage0/MINI_SM_NTSC.bin stage1.bin
App settings:
        SDP_CB: 0x811731E0
        L2CB: 0x811725E0
        SWITCH_ADDR: 0x8168EE98
Opening device hci0
Setting device local name
Error binding to l2cap socket: Address already in use

**Comment by holadivinus** [comment]
heres my hci0 info 

[hci0]# info
hci0:   Primary controller
        addr B8:27:EB:77:93:69 version 9 manufacturer 305 class 0x000000
        supported settings: powered connectable fast-connectable discoverable bondable link-security ssp br/edr hs le advertising secure-conn debug-keys privacy static-addr
        current settings: powered bondable ssp br/edr le secure-conn
        name Nintendo RVL-CNT-01
        short name
[hci0]#

**Comment by Fullmetal5** [comment]
You can use Bluebomb as many times as you want in a row, something is just using the port it needs.
Try running `sudo systemctl disable --now bluetooth` again and then seeing if the port it still in use.

**Comment by holadivinus** [comment]
there isnt a .bin for a normal wii ?!?!

**Comment by holadivinus** [comment]
MINI_SM_NTSC.bin doesnt work on a full wii

**Comment by Fullmetal5** [comment]
Oops, sorry, I forgot to add the normal Wii's stage0.bin's in when they were created, they are now included in the bluebomb.zip

**Comment by holadivinus** [comment]
?
its not there...
can you link me to it? sorry

**Comment by Fullmetal5** [comment]
https://github.com/Fullmetal5/bluebomb/releases/download/v1.0/bluebomb.zip

**Comment by holadivinus** [comment]
Thank you so much im in a hurry goodbye

**Comment by holadivinus** [comment]
This program just unbricked my "un-unbrickable" wii! :D
Thank you so much 

:)

**Comment by Fullmetal5** [comment]
Happy it worked. Now you should really install priiloader+bootmii and make a nand backup so this doesn't happen again. :P
