### ISSUE TITLE
Couldn’t mount usb key

### ISSUE THREAD

**Issue by ghost** [Fullmetal5/bluebomb#16]
So i have my usb key formated to Fat32 and after doing the hack, the program try to launch the boot file that are on the usb but it say « couldnt mount usb key ». What habe i done wrong ?

Ps : I’ve formatted the usb key to Fat32 on a mac, can this be the source of this problem ?

**Comment by Fullmetal5** [comment]
Make sure the usb was formatted as MBR FAT32 and not GPT FAT32.
Try following these instructions to format the usb and then put the files back on it and see if it works: https://www.easeus.com/mac-file-recovery/format-usb-flash-drive-to-fat32-on-mac.html#1

**Comment by ghost** [comment]
Thank you for the fast answer, I'm gonna try

**Comment by ghost** [comment]
This was the issue ! Thank you very much for your help😄
