### ISSUE TITLE
Bluetooth device shared but cant disable service

### ISSUE THREAD

**Issue by DraftmanCorp** [Fullmetal5/bluebomb#17]
Hello,
I have last virtual box and Linux Lite 4.6 (x64).
Under Device/USB/ I can find and share Bluetooth adapter correctly.
But when i perform **sudo systemctl disable --now bluetooth** i get this:

Synchronizing state of bluetooth.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable bluetooth
insserv: warning: current start runlevel(s) (empty) of script `bluetooth' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `bluetooth' overrides LSB defaults (0 1 6).
insserv: warning: current start runlevel(s) (empty) of script `bluetooth' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `bluetooth' overrides LSB defaults (0 1 6).

nothing more.
and the next command ( **sudo ./bluebomb-x86 ./stage0/MINI_SM_PAL.bin stage1.bin** ) fail with no such devices.
I tried sudo apt-get update and sudo apt-get upgrade.
Have you suggestion please?

**Comment by nivibilla** [comment]
if you are using a VM, select usb devices and select your usb controller for the bluetooth:
https://scribles.net/enabling-bluetooth-in-virtualbox/
Then try: 'hciconfig -a' it should comeup with a list of bluetooth configurations. and also say status is down.
if it doesnt show that then your vm isnt recognising the bluetooth

**Comment by DraftmanCorp** [comment]
thanks, i was using the wrong usb adapter.
sorry.
can close.

**Comment by nivibilla** [comment]
no worries, ill try improve the readme for other people trying this, got the same problem yesterday when trying to mod my wii mini.
