### ISSUE TITLE
Will Nintendont work on the Wii Mini?

### ISSUE THREAD

**Issue by ghost** [Fullmetal5/bluebomb#18]

**Comment by piratesephiroth** [comment]
You should ask this kind of questions on forums like gbatemp.
That sort of thing has no relation to the bluebomb project

https://gbatemp.net/threads/does-nintendont-working-on-wii-mini.550438/

**Comment by Fullmetal5** [comment]
piratesephiroth is correct, this is not the place for discussion of these things.
