### ISSUE TITLE
Can you use BlueZ on Windows (10) via WSL and by extension BlueBomb?

### ISSUE THREAD

**Issue by fancythedeveloper** [Fullmetal5/bluebomb#6]

**Comment by Leseratte10** [comment]
I haven't tested it, but I highly doubt it. I don't think WSL supports full passthrough of a Bluetooth adapter. It'd probably be better to use a virtual machine or a Linux live CD.

**Comment by fancythedeveloper** [comment]
Didn't expect a quick response, hello Leseratte! Anyways, yea, kinda expected that answer. My brother's laptop does have a Ubuntu dualboot, so I'ma try that.
