### ISSUE TITLE
ARM build / compile script?

### ISSUE THREAD

**Issue by tomrow** [Fullmetal5/bluebomb#8]
Is it possible to also release ARM RaspberryPi builds of this, or some sort of easy compile script that one can download and run? I'm not really willing to mess up my UEFI settings for Windows just to hack a Wii
These ARM machines tend to be much more expendable than x86 machines and are easily fixed when they break

**Comment by Leseratte10** [comment]
There already is a "compile script", the Makefile. Just install gcc and make (`sudo apt install make gcc`), and maybe some more libraries like `libbluetooth-dev` and you should be able to compile it by executing `make`.

**Comment by Fullmetal5** [comment]
ARM builds will be available in the next build, once I get my Pi working again. :P
